name: Deploy to Firebase Hosting on PR

on:
  pull_request_target:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write

    steps:
      - uses: actions/checkout@v2

      - name: Write google-services.json file
        run: |
          cd composeApp
          echo $GOOGLE_SERVICES | base64 -d > google-services.json
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

      - name: Write key.properties file
        run: |
          echo $KEY_PROPERTIES | base64 -d > composeApp/src/androidMain/key.properties
        shell: bash
        env:
          KEY_PROPERTIES: ${{ secrets.KEY_PROPERTIES }}

      # Ensure JDK 17 is set up to match the Firebase Crashlytics Gradle plugin
      # requirements
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin' # Eclipse Temurin https://adoptium.net/

      # Run the Gradle task for building the web distribution
      - name: Build Web Distribution
        run: ./gradlew wasmJsBrowserDistribution

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MALA_KNYZHKA }}'
          projectId: mala-knyzhka
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels